### ISSUE TITLE
expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by Devin100086** [silent-chen/DGE#11]
Dear authors, thank you for your impressive work.

I encountered an issue during training. "expected scalar type Float but found BFloat16",How can I resolve it?

Thank you

**Comment by silent-chen** [comment]
Hi, can you provide more detailed errors?

**Comment by Devin100086** [comment]
Thanks, I have solved my problems！

**Comment by WarrenZZZZL** [comment]
> Thanks, I have solved my problems！

Hi, I also encountered this problem. How did you solve this problem? Thank you, Devin!

**Comment by Devin100086** [comment]
you should specially `pip install gaussiansplatting/submodules/diff-gaussian-rasterization` and `pip install gaussiansplatting/submodules/simple-knn`. And you should set` projmatrix=viewpoint_camera.full_proj_transform.float() `in the line 83 of the `gaussiansplatting/gaussian_renderer/__init__.py` file.

**Comment by WarrenZZZZL** [comment]
very useful!!! Thank your contribution!!!
