### ISSUE TITLE
 IN2N data or process code

### ISSUE THREAD

**Issue by Alex-Zhu1** [silent-chen/DGE#12]
HI, nice work. can u provide  person-small data, or share your code for processing code?

i found colmap data of IN2N is broken.  can u help me or give some sugg?

Thanks a lot!!

**Comment by silent-chen** [comment]
Thanks for your interests in our work.

Here is the data I use.

https://drive.google.com/file/d/1l-lESvSf7_0bXOO_a8lQZ-nVqSt0pC15/view?usp=drive_link
