### ISSUE TITLE
Get edited 3D Gaussians

### ISSUE THREAD

**Issue by haoyuhsu** [silent-chen/DGE#3]
Hi,

I really appreciate the nice & fast local editing showcased in this paper, and I have tried it recently.

I would like to render the edited 3D Gaussians with a custom camera trajectory. Are the 3D gaussians saved as `last.ply` under the output folder `MY_EDIT_PROMPT@TIMESTAMP/save`?

Thanks!

**Comment by silent-chen** [comment]
Hi,

Thanks for your interest in our work. 

Yes! It is saved as `last.ply` as stated [here](https://github.com/silent-chen/DGE/blob/1149c3a72102e3db33d626cb3ea7d228b836e68d/threestudio/systems/DGE.py#L495). 

Best,
Minghao

**Comment by haoyuhsu** [comment]
Gotcha! Thank you!
