### ISSUE TITLE
Question about the code in "dge_guidance.py"

### ISSUE THREAD

**Issue by cyf066** [silent-chen/DGE#4]
Hi,

I have a question regarding the code in dge_guidance.py at line 122. Should this function be placed outside the loop?
https://github.com/silent-chen/DGE/blob/1149c3a72102e3db33d626cb3ea7d228b836e68d/threestudio/models/guidance/dge_guidance.py#L122
Thank you!

**Comment by cyf066** [comment]
。

**Comment by silent-chen** [comment]
Thanks! Yes, you can do it outside the loop and it will not cause differences in results.
