### ISSUE TITLE
View my edited result

### ISSUE THREAD

**Issue by yoyoNTNU** [silent-chen/DGE#5]
Hello, As a newcomer to this field, I want to know how can I view my edited result, should I use SIBR viewer? Thank you.

**Comment by silent-chen** [comment]
Hi, thanks for your interest in our work. We render the edited GS at `output/MY_EDIT_PROMPT@TIMESTAMP/save`. You can also view it with SIBR or other viewer. The edited gaussian is saved as `last.ply`.
