### ISSUE TITLE
add dge to huggingface hub

### ISSUE THREAD

**Issue by jadechoghari** [silent-chen/DGE#6]
Hello,
DGE sounds very interesting—congrats on the paper!!
I wonder if you would consider adding dge to the Hugging Face Hub. Doing so increase the model's visibility and make it easier for everyone to use!
It can be easily compatible with the Hugging Face Transformers library.

Can work on that!
Goal: Make AI open and accessible to all 🤗

Best, 
Jade

**Comment by jadechoghari** [comment]
will ping @silent-chen

**Comment by silent-chen** [comment]
Hi Jade,

Thanks for your interest in our paper! I completely agree with you - adding DGE to the Hugging Face Hub would be really helpful in increasing its visibility and accessibility.

However, I'm not sure about the specifics of integrating it into the Hugging Face Transformers library at this point.

If you'd be willing to collaborate on this effort, that would be fantastic! We could work together to explore any potential challenges and make it happen.

Best,
Minghao

**Comment by jadechoghari** [comment]
Yes, of course, I can do the work (with the help of the Hugging Face team)! 
If I encounter any issues or have questions during the implementation, I'll let you know.

**Comment by silent-chen** [comment]
Thank you, Jade! 
Feel free to let me know if you have any issues.

**Comment by jadechoghari** [comment]
great! will send you a mail!
