### ISSUE TITLE
Can u provide the sample data and pretrained 3dGS for testing? thanks.

### ISSUE THREAD

**Issue by lvZic** [silent-chen/DGE#7]

**Comment by silent-chen** [comment]
Sure. I uploaded an example of the input to the google cloud: https://drive.google.com/drive/folders/1w5apQMBAfC3iciGexQ-dmpBtj4Y8ibwD?usp=sharing

You can unzip the file in the link and run command like following to get result of turning the man into a Vincent Van Gogh:

python launch.py --config configs/dge.yaml --train --gpu 0 trainer.max_steps=1500 system.prompt_processor.prompt="Make him look like Vincent Van Gogh" data.source="./face/" system.guidance.guidance_scale=10.0 system.gs_source="./face/scene_point_cloud.ply"

**Comment by lvZic** [comment]
> Sure. I uploaded an example of the input to the google cloud: https://drive.google.com/drive/folders/1w5apQMBAfC3iciGexQ-dmpBtj4Y8ibwD?usp=sharing
> 
> You can unzip the file in the link and run command like following to get result of turning the man into a Vincent Van Gogh:
> 
> python launch.py --config configs/dge.yaml --train --gpu 0 trainer.max_steps=1500 system.prompt_processor.prompt="Make him look like Vincent Van Gogh" data.source="./face/" system.guidance.guidance_scale=10.0 system.gs_source="./face/scene_point_cloud.ply"

thanks for your reply.
I met following problem after following your steps in ReadMe. 
"ImportError: /mnt/workspace/lvzhen/Bin/Conda_Env/DGE/lib/python3.10/site-packages/diff_gaussian_rasterization/_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c1015SmallVectorBaseIjE8grow_podEPvmm".
cuda 11.8, following is the env:
![image](https://github.com/user-attachments/assets/dac85aab-bb00-44fa-b131-4a2063f9c1a0)

**Comment by lvZic** [comment]
> Sure. I uploaded an example of the input to the google cloud: https://drive.google.com/drive/folders/1w5apQMBAfC3iciGexQ-dmpBtj4Y8ibwD?usp=sharing
> 
> You can unzip the file in the link and run command like following to get result of turning the man into a Vincent Van Gogh:
> 
> python launch.py --config configs/dge.yaml --train --gpu 0 trainer.max_steps=1500 system.prompt_processor.prompt="Make him look like Vincent Van Gogh" data.source="./face/" system.guidance.guidance_scale=10.0 system.gs_source="./face/scene_point_cloud.ply"

thanks
